=== EnjoyFX/uarates_data/data/v1/schema/index.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://enjoyfx.github.io/uarates_data/v1/schema/index.schema.json",
  "title": "Каталог валют",
  "type": "object",
  "required": [
    "schema",
    "source",
    "updated_at",
    "last_date",
    "currencies"
  ],
  "properties": {
    "schema": {
      "const": 1
    },
    "source": {
      "type": "string",
      "format": "uri"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "description": "Коли дані востаннє змінювались (UTC)"
    },
    "last_date": {
      "type": "string",
      "format": "date",
      "description": "Найпізніша дата, на яку є курс"
    },
    "currencies": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "code",
          "r030",
          "name",
          "name_en",
          "units",
          "first_date",
          "last_date",
          "quoted",
          "updated_at"
        ],
        "additionalProperties": false,
        "properties": {
          "code": {
            "type": "string",
            "pattern": "^[A-Z]{3}$",
            "description": "Літерний код валюти ISO 4217"
          },
          "r030": {
            "type": [
              "integer",
              "null"
            ],
            "description": "Цифровий код валюти ISO 4217"
          },
          "name": {
            "type": [
              "string",
              "null"
            ],
            "description": "Назва валюти українською (за НБУ)"
          },
          "name_en": {
            "type": [
              "string",
              "null"
            ],
            "description": "Назва валюти англійською (за НБУ)"
          },
          "units": {
            "type": "integer",
            "minimum": 1,
            "description": "Поточна кількість одиниць котирування"
          },
          "first_date": {
            "type": "string",
            "format": "date"
          },
          "last_date": {
            "type": "string",
            "format": "date"
          },
          "quoted": {
            "type": "boolean",
            "description": "Чи котирує НБУ валюту зараз"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "description": "Коли дані востаннє змінювались (UTC)"
          }
        }
      }
    }
  }
}

=== EnjoyFX/uarates_data/data/v1/index.json
{
  "schema": 1,
  "source": "https://bank.gov.ua",
  "updated_at": "2026-10-23T17:10:34Z",
  "last_date": "2026-10-26",
  "currencies": [
    {
      "code": "AED",
      "r030": 784,
      "name": "Дирхам ОАЕ",
      "name_en": "UAE Dirham",
      "units": 1,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "AUD",
      "r030": 36,
      "name": "Австралійський долар",
      "name_en": "Australian Dollar",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "AZN",
      "r030": 944,
      "name": "Азербайджанський манат",
      "name_en": "Azerbaijan Manat",
      "units": 1,
      "first_date": "2014-04-04",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "BDT",
      "r030": 50,
      "name": "Така",
      "name_en": "Taka",
      "units": 10,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "CAD",
      "r030": 124,
      "name": "Канадський долар",
      "name_en": "Canadian Dollar",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "CHF",
      "r030": 756,
      "name": "Швейцарський франк",
      "name_en": "Swiss Franc",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "CNY",
      "r030": 156,
      "name": "Юань Женьміньбі",
      "name_en": "Yuan Renminbi ",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "CZK",
      "r030": 203,
      "name": "Чеська крона",
      "name_en": "Czech Koruna",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "DKK",
      "r030": 208,
      "name": "Данська крона",
      "name_en": "Danish Krone",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "DZD",
      "r030": 12,
      "name": "Алжирський динар",
      "name_en": "Algerian Dinar",
      "units": 10,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "EGP",
      "r030": 818,
      "name": "Єгипетський фунт",
      "name_en": "Egyptian Pound",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "EUR",
      "r030": 978,
      "name": "Євро",
      "name_en": "Euro",
      "units": 1,
      "first_date": "1999-01-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "GBP",
      "r030": 826,
      "name": "Фунт стерлінгів",
      "name_en": "Pound Sterling",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "GEL",
      "r030": 981,
      "name": "Ларі",
      "name_en": "Lari",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "HKD",
      "r030": 344,
      "name": "Гонконгівський долар",
      "name_en": "Hong Kong Dollar",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "HUF",
      "r030": 348,
      "name": "Форинт",
      "name_en": "Forint",
      "units": 100,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "IDR",
      "r030": 360,
      "name": "Рупія",
      "name_en": "Rupiah",
      "units": 1000,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "ILS",
      "r030": 376,
      "name": "Новий ізраїльський шекель",
      "name_en": "New Israeli Sheqel",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "INR",
      "r030": 356,
      "name": "Індійська рупія",
      "name_en": "Indian Rupee",
      "units": 10,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "JPY",
      "r030": 392,
      "name": "Єна",
      "name_en": "Yen",
      "units": 10,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "KRW",
      "r030": 410,
      "name": "Вона",
      "name_en": "Won",
      "units": 100,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "KZT",
      "r030": 398,
      "name": "Теньге",
      "name_en": "Tenge",
      "units": 100,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "LBP",
      "r030": 422,
      "name": "Ліванський фунт",
      "name_en": "Lebanese Pound",
      "units": 100,
      "first_date": "1998-04-07",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "MDL",
      "r030": 498,
      "name": "Молдовський лей",
      "name_en": "Moldovan Leu",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "MXN",
      "r030": 484,
      "name": "Мексиканське песо",
      "name_en": "Mexican Peso",
      "units": 1,
      "first_date": "1998-04-07",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "MYR",
      "r030": 458,
      "name": "Малайзійський ринггіт",
      "name_en": "Malaysian Ringgit",
      "units": 1,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "NOK",
      "r030": 578,
      "name": "Норвезька крона",
      "name_en": "Norwegian Krone",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "NZD",
      "r030": 554,
      "name": "Новозеландський долар",
      "name_en": "New Zealand Dollar",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "PLN",
      "r030": 985,
      "name": "Злотий",
      "name_en": "Zloty",
      "units": 1,
      "first_date": "1997-11-12",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "RON",
      "r030": 946,
      "name": "Румунський лей",
      "name_en": "Romanian Leu",
      "units": 1,
      "first_date": "2014-05-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "RSD",
      "r030": 941,
      "name": "Сербський динар",
      "name_en": "Serbian Dinar",
      "units": 10,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "SAR",
      "r030": 682,
      "name": "Саудівський ріял",
      "name_en": "Saudi Riyal",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "SEK",
      "r030": 752,
      "name": "Шведська крона",
      "name_en": "Swedish Krona",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "SGD",
      "r030": 702,
      "name": "Сінгапурський долар",
      "name_en": "Singapore Dollar",
      "units": 1,
      "first_date": "1996-09-02",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "THB",
      "r030": 764,
      "name": "Бат",
      "name_en": "Baht",
      "units": 10,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "TND",
      "r030": 788,
      "name": "Туніський динар",
      "name_en": "Tunisian Dinar",
      "units": 1,
      "first_date": "2016-11-01",
      "last_date": "2026-10-26",
      "quoted": true,
      "updated_at": "2026-10-23T17:10:34Z"
    },
    {
      "code": "TRY",
      "r030": 949,
      "name": "Турецька ліра",
      "name_en": "Turkish Lira",
      "units": 1,
      "first_date": "2014-04-04",
      "last_date": "2026-10-26",
      "quoted": true,
